services:
  livy-ui:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/ervijayraghuwanshi/livy-ui:latest
    container_name: livy-ui
    ports:
      - '4173:4173'
    restart: unless-stopped