services:

  livy:
      build: 
        context: .
        dockerfile: DockerfileLivy
      container_name: livy-server
      hostname: livy-server
      environment:
        - SPARK_PUBLIC_DNS=localhost
      ports:
        - '8998:8998'
        - '4040-4050:4040-4050'  # <--- Map a range for multiple sessions
        - '18080:18080'  # Spark History Server UI
      volumes:
        - ./data:/opt/spark/data
        - ./work-dir:/opt/spark/work-dir
        - ./livy.conf:/opt/livy/conf/livy.conf
        - ./spark-events:/tmp/spark-events  # Persistent storage for Spark event logs

  livy-ui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_REPO: https://github.com/ErVijayRaghuwanshi/livy-ui.git
        GIT_BRANCH: main
    container_name: livy-ui
    ports:
      - '4173:4173'
    depends_on:
      - livy