services:

  spark:
    build:
      context: ./spark
      dockerfile: Dockerfile.spark
    container_name: spark-master
    hostname: spark-master
    environment:
      - SPARK_PUBLIC_DNS=localhost
    ports:
      - '7077:7077'
      - '8080:8080'      # Spark Master UI
      - '18080:18080'    # Spark History Server UI
    volumes:
      - ./spark/data:/opt/spark/data
      - ./spark/work-dir:/opt/spark/work-dir
      - ./spark/spark-events:/tmp/spark-events  # Persistent storage for Spark event logs
    networks:
      - data-platform

  livy:
    build:
      context: ./spark
      dockerfile: Dockerfile.livy
    container_name: livy-server
    hostname: livy-server
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_PUBLIC_DNS=localhost
    ports:
      - '8998:8998'        # Livy API & Nginx CORS Proxy
      - '4040-4050:4040-4050'  # Map range for Spark driver UIs
    volumes:
      - ./spark/data:/opt/spark/data
      - ./spark/work-dir:/opt/spark/work-dir
      - ./spark/livy.conf:/opt/livy/conf/livy.conf
      - ./spark/spark-events:/tmp/spark-events
    depends_on:
      - spark
    networks:
      - data-platform

  livy-ui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_REPO: https://github.com/ErVijayRaghuwanshi/livy-ui.git
        GIT_BRANCH: feature/v1.5.0
    container_name: livy-ui
    ports:
      - '4173:4173'
    depends_on:
      - livy
    networks:
      - data-platform


# ==============================================================================
# Network & Volume Bindings
# ==============================================================================
networks:
  data-platform:
    driver: bridge
    name: data-platform