# Network & Security
livy.server.csrf_protection.enabled = false
livy.server.cors.enabled = true
livy.server.cors.allowed-origins = *
livy.server.cors.allowed-methods = GET,POST,DELETE,PUT
livy.server.access-control.allow-origin = *
livy.server.access-control.allow-methods = GET, POST, OPTIONS, DELETE
livy.server.cors.allowed-headers = Content-Type,X-Requested-With

# Cluster Configuration
# livy.spark.master = spark://spark-master:7077
livy.spark.master = local[*]
livy.server.port = 8998
livy.server.host = 0.0.0.0


livy.rsc.sql.num-rows=5000


# Set the Spark home directory to match the one in the Docker image
livy.spark.home = /opt/spark

# Ensure the Driver UI binds to an address reachable by Docker
livy.spark.ui.enabled = true
livy.spark.ui.port = 4040
livy.spark.driver.host = localhost
# Optional: Set the max number of retries for port binding to match your Docker range
livy.spark.port.maxRetries = 10

# Increase the size of the logs Livy keeps (default is often 10MB)
livy.cache-log.size = 10000

# Enable Hive context for Livy REPL
livy.repl.enable-hive-context = true

# Spark session defaults that must apply to every Livy-created session are
# defined in /opt/spark/conf/spark-defaults.conf inside the image.

# Add the directory containing our custom UDFs to the pyFiles configuration so they are automatically distributed to all Spark executors when a session is created.
livy.spark.session.init.pyFiles=/opt/spark/spark_udfs/spark_init.py