FROM apache/spark:3.5.4

USER root

# Install system dependencies
RUN apt-get update && apt-get install -y wget procps python3 openjdk-11-jdk-headless && rm -rf /var/lib/apt/lists/*

# Install Kafka connector for Spark 3.5
RUN wget -P /opt/spark/jars/ \
https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.5.4/spark-sql-kafka-0-10_2.12-3.5.4.jar && \
wget -P /opt/spark/jars/ \
https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.5.4/spark-token-provider-kafka-0-10_2.12-3.5.4.jar && \
wget -P /opt/spark/jars/ \
https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.5.1/kafka-clients-3.5.1.jar && \
wget -P /opt/spark/jars/ \
https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.12.0/commons-pool2-2.12.0.jar

# Add PostgreSQL driver
RUN wget -P /opt/spark/jars/ https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.4/postgresql-42.7.4.jar

# Add Delta Lake jars
RUN wget -P /opt/spark/jars/ \
https://repo1.maven.org/maven2/io/delta/delta-spark_2.12/3.2.0/delta-spark_2.12-3.2.0.jar && \
wget -P /opt/spark/jars/ \
https://repo1.maven.org/maven2/io/delta/delta-storage/3.2.0/delta-storage-3.2.0.jar

# Add Sedona jars
RUN wget -P /opt/spark/jars/ \
https://repo1.maven.org/maven2/org/apache/sedona/sedona-spark-shaded-3.5_2.12/1.7.0/sedona-spark-shaded-3.5_2.12-1.7.0.jar && \
wget -P /opt/spark/jars/ \
https://repo1.maven.org/maven2/org/datasyslab/geotools-wrapper/1.7.0-28.5/geotools-wrapper-1.7.0-28.5.jar

# Create directory for Spark event logs
RUN mkdir -p /tmp/spark-events && \
    chown -R 185:185 /tmp/spark-events

COPY start-spark.sh /opt/start-spark.sh
RUN chmod +x /opt/start-spark.sh && chown 185:185 /opt/start-spark.sh

USER 185

ENV SPARK_HOME=/opt/spark
ENV PYSPARK_PYTHON=python3
ENV PYSPARK_DRIVER_PYTHON=python3
ENV SPARK_HISTORY_OPTS="-Dspark.history.fs.logDirectory=/tmp/spark-events -Dspark.history.ui.port=18080"

EXPOSE 7077 8080 18080

CMD ["/opt/start-spark.sh"]
