# Structured Streaming Kafka and Avro integration jar packages for Spark 3.5, along with Apache Sedona and PostgreSQL JDBC
spark.jars.packages              io.delta:delta-spark_2.12:3.2.0,org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.4,org.apache.spark:spark-avro_2.12:3.5.4,org.apache.sedona:sedona-spark-shaded-3.5_2.12:1.7.0,org.postgresql:postgresql:42.7.4

# Enable Apache Sedona & Delta Lake SQL Extensions
spark.sql.extensions             org.apache.sedona.sql.SedonaSqlExtensions,io.delta.sql.DeltaSparkSessionExtension

# Persistent Ivy cache directory (mounted to volume in docker-compose)
spark.jars.ivy                   /tmp/.ivy

# Enable Event Logging for Spark History Server
spark.eventLog.enabled           true
spark.eventLog.dir               file:/opt/spark/event_logs

# Enable Delta Lake catalog support
spark.sql.catalog.spark_catalog  org.apache.spark.sql.delta.catalog.DeltaCatalog

# Metastore and Warehouse Persistence
spark.sql.catalogImplementation          hive
spark.sql.warehouse.dir                  file:/opt/spark/warehouse
spark.hadoop.javax.jdo.option.ConnectionURL jdbc:derby:/opt/spark/metastore/metastore_db;create=true
spark.hadoop.javax.jdo.option.ConnectionDriverName org.apache.derby.jdbc.EmbeddedDriver
