# Structured Streaming Kafka and Avro integration jar packages for Scala 2.13, along with Apache Sedona and PostgreSQL JDBC
spark.jars.packages              io.delta:delta-spark_4.1_2.13:4.1.0,org.apache.spark:spark-sql-kafka-0-10_2.13:4.1.2,org.apache.spark:spark-avro_2.13:4.1.2,org.apache.sedona:sedona-spark-shaded-4.1_2.13:1.9.0,org.postgresql:postgresql:42.7.3

# Enable Apache Sedona & Delta Lake SQL Extensions
spark.sql.extensions             org.apache.sedona.sql.SedonaSqlExtensions,io.delta.sql.DeltaSparkSessionExtension

# Persistent Ivy cache directory (mounted to volume in docker-compose)
spark.jars.ivy                   /tmp/.ivy

# Enable Event Logging for Spark History Server
spark.eventLog.enabled           true
spark.eventLog.dir               file:/opt/spark/event_logs

# Enable Delta Lake support
spark.sql.catalog.spark_catalog  org.apache.spark.sql.delta.catalog.DeltaCatalog

# Metastore and Warehouse Persistence
spark.sql.catalogImplementation          hive
spark.sql.warehouse.dir                  file:/opt/spark/warehouse
spark.hadoop.javax.jdo.option.ConnectionURL jdbc:derby:/opt/spark/metastore/metastore_db;create=true
spark.hadoop.javax.jdo.option.ConnectionDriverName org.apache.derby.jdbc.EmbeddedDriver

# Compute Resource Cluster Defaults
spark.executor.cores             4
spark.executor.memory            2g
spark.driver.memory              2g
