export const SPARK_SQL_SNIPPETS = [
  {
    label: "create_table_parquet",
    description: "Create a table using Parquet format",
    insertText: [
      "CREATE TABLE IF NOT EXISTS default.${1:table_name}",
      "USING parquet",
      "LOCATION '${2:hdfs://namenode/path/to/data}';",
    ].join("\n"),
  },
  {
    label: "create_view_csv",
    description: "Create a temporary view from a CSV file",
    insertText: [
      "CREATE TABLE IF NOT EXISTS default.${1:customers} ",
      "USING csv ",
      "OPTIONS (",
      "  path '${2:/opt/spark/data/customers.csv}', ",
      "  header '${3:true}', ",
      "  inferSchema '${4:true}'",
      ");",
    ].join("\n"),
  },
  {
    label: "create_view_json",
    description: "Create a temporary view from a JSON file",
    insertText: [
      "CREATE TEMPORARY VIEW ${1:view_name} ",
      "USING json ",
      "OPTIONS (",
      "  path '${2:/opt/spark/data/file.json}'",
      ");",
    ].join("\n"),
  },
  {
    label: "select_limit",
    description: "Basic SELECT query with LIMIT",
    insertText: "SELECT * FROM ${1:table_name} LIMIT ${2:10};",
  },
  {
    label: "targets_example",
    description: "Pre-filled example with 10 sample targets for quick testing",
    insertText: [
      "WITH raw AS (",
      "  SELECT from_json(",
      "    '[{\"9811002233\": {\"target_name\": \"VIP Exec Global\"}}, {\"9123456789\": {\"target_name\": \"Gateway Node East\"}}, {\"8800112244\": {\"target_name\": \"Staff Admin Alpha\"}}, {\"7042556677\": {\"target_name\": \"Sensor Fleet 01\"}}, {\"9988776655\": {\"target_name\": \"Retail POS Terminal\"}}, {\"6300445566\": {\"target_name\": \"Subject HighRisk 102\"}}, {\"8122334455\": {\"target_name\": \"Field Agent North\"}}, {\"9876543210\": {\"target_name\": \"Sentinel Test Probe\"}}, {\"7500119922\": {\"target_name\": \"Data Intensive User\"}}, {\"9011223344\": {\"target_name\": \"International Hub 05\"}}]',",
      "    'array<map<string,struct<target_name:string>>>'",
      "  ) AS arr",
      "),",
      "targets AS (",
      "  SELECT",
      "    target_entry.key AS mobile_number,",
      "    target_entry.value.target_name AS target_name",
      "  FROM raw",
      "  LATERAL VIEW EXPLODE(arr) a AS target_map",
      "  LATERAL VIEW EXPLODE(MAP_ENTRIES(target_map)) t AS target_entry",
      ")",
      "SELECT * FROM targets;",
    ].join("\n"),
  },
  {
    label: "target_json_value",
    description: "Sample JSON value with 10 targets for from_json",
    insertText: '[{"9811002233": {"target_name": "VIP Exec Global"}}, {"9123456789": {"target_name": "Gateway Node East"}}, {"8800112244": {"target_name": "Staff Admin Alpha"}}, {"7042556677": {"target_name": "Sensor Fleet 01"}}, {"9988776655": {"target_name": "Retail POS Terminal"}}, {"6300445566": {"target_name": "Subject HighRisk 102"}}, {"8122334455": {"target_name": "Field Agent North"}}, {"9876543210": {"target_name": "Sentinel Test Probe"}}, {"7500119922": {"target_name": "Data Intensive User"}}, {"9011223344": {"target_name": "International Hub 05"}}]',
  },
  {
    label: "targets_json",
    description: "Inline JSON target lookup table using from_json + LATERAL VIEW",
    insertText: [
      "WITH raw AS (",
      "  SELECT from_json(",
      "    '[{\"${1:mobile}\": {\"target_name\": \"${2:Name}\"}}]',",
      "    'array<map<string,struct<target_name:string>>>'",
      "  ) AS arr",
      "),",
      "targets AS (",
      "  SELECT",
      "    target_entry.key AS mobile_number,",
      "    target_entry.value.target_name AS target_name",
      "  FROM raw",
      "  LATERAL VIEW EXPLODE(arr) a AS target_map",
      "  LATERAL VIEW EXPLODE(MAP_ENTRIES(target_map)) t AS target_entry",
      ")",
      "SELECT * FROM targets;",
    ].join("\n"),
  },
  {
    label: "rule_vpn_tor_usage",
    description: "Anomaly detection rule: VPN/TOR usage by targets",
    insertText: [
      "WITH raw AS (",
      "  SELECT from_json(",
      "    '${1:[{\"mobile\": {\"target_name\": \"Name\"}}]}',",
      "    'array<map<string,struct<target_name:string>>>'",
      "  ) AS arr",
      "),",
      "targets AS (",
      "  SELECT",
      "    target_entry.key AS mobile_number,",
      "    target_entry.value.target_name AS target_name",
      "  FROM raw",
      "  LATERAL VIEW EXPLODE(arr) a AS target_map",
      "  LATERAL VIEW EXPLODE(MAP_ENTRIES(target_map)) t AS target_entry",
      "),",
      "target_data_filter AS (",
      "  SELECT",
      "    MOBILENUMBER,",
      "    CASE WHEN DOMAINCATID = '98' THEN 'TOR' ELSE 'VPN' END AS VPN_TOR,",
      "    TRANSACTIONSTARTTIME,",
      "    DATE",
      "  FROM parquet.\\`${2:hdfs://namenode/path/to/data}\\`",
      "  WHERE MOBILENUMBER IS NOT NULL",
      "    AND DOMAINCATID IN ('98', '99')",
      "    AND DATE IN ('${3:2026-01-01}')",
      "),",
      "rule_data AS (",
      "  SELECT",
      "    v.MOBILENUMBER, v.VPN_TOR, v.TRANSACTIONSTARTTIME, v.DATE, t.target_name",
      "  FROM target_data_filter v",
      "  INNER JOIN targets t ON v.MOBILENUMBER = t.mobile_number",
      ")",
      "SELECT",
      "  concat(MOBILENUMBER, '-AID-7-', VPN_TOR, DATE) AS id,",
      "  MOBILENUMBER AS MobileNumber,",
      "  target_name AS TargetName,",
      "  '7' AS RuleId,",
      "  'VPN TOR Usage.' AS RuleName,",
      "  'TOR VPN usage' AS GroupRuleName,",
      "  '${4:GroupId}' AS GroupId,",
      "  '${5:GroupName}' AS GroupName,",
      "  'RULE' AS GroupType,",
      "  '5' AS TrainingPeriod,",
      "  'EVIDENCE' AS Evidence,",
      "  DATE AS Date,",
      "  'VPN_TOR' AS BehaviourMetricType,",
      "  VPN_TOR AS BehaviourMetricKey,",
      "  count(*) AS BehaviourMetricValue,",
      "  'Target using VPN/TOR applications.' AS AnomalyDescription,",
      "  'Transaction' AS AnomalyIdentifiedLevel,",
      "  '[]' AS ThresholdValueList,",
      "  min(TRANSACTIONSTARTTIME) AS FirstSeenStartTime,",
      "  max(TRANSACTIONSTARTTIME) AS LastSeenStartTime",
      "FROM rule_data",
      "GROUP BY MOBILENUMBER, VPN_TOR, DATE, target_name",
      "HAVING BehaviourMetricValue >= ${6:1}",
    ].join("\n"),
  },
  {
    label: "rule_template",
    description: "Generic anomaly detection rule template with configurable parameters",
    insertText: [
      "WITH raw AS (",
      "  SELECT from_json(",
      "    '${1:TARGETS}',",
      "    'array<map<string,struct<target_name:string>>>'",
      "  ) AS arr",
      "),",
      "targets AS (",
      "  SELECT",
      "    target_entry.key AS mobile_number,",
      "    target_entry.value.target_name AS target_name",
      "  FROM raw",
      "  LATERAL VIEW EXPLODE(arr) a AS target_map",
      "  LATERAL VIEW EXPLODE(MAP_ENTRIES(target_map)) t AS target_entry",
      "),",
      "target_data_filter AS (",
      "  SELECT",
      "    MOBILENUMBER,",
      "    CASE WHEN DOMAINCATID = '98' THEN 'TOR' ELSE 'VPN' END AS VPN_TOR,",
      "    TRANSACTIONSTARTTIME,",
      "    DATE",
      "  FROM ${2:MASS}",
      "  WHERE MOBILENUMBER IS NOT NULL",
      "    AND DOMAINCATID IN ('98', '99')",
      "    AND DATE IN ('${3:DATE}')",
      "),",
      "rule_data AS (",
      "  SELECT",
      "    v.MOBILENUMBER, v.VPN_TOR, v.TRANSACTIONSTARTTIME, v.DATE, t.target_name",
      "  FROM target_data_filter v",
      "  INNER JOIN targets t ON v.MOBILENUMBER = t.mobile_number",
      ")",
      "SELECT",
      "  concat(MOBILENUMBER, '-AID-${4:RULE_ID}-', VPN_TOR, DATE) AS id,",
      "  MOBILENUMBER AS MobileNumber,",
      "  target_name AS TargetName,",
      "  '${4:RULE_ID}' AS RuleId,",
      "  '${5:RULE_NAME}' AS RuleName,",
      "  '${6:UNIQUE_NAME}' AS GroupRuleName,",
      "  '${7:GROUP_ID}' AS GroupId,",
      "  '${8:GROUP_NAME}' AS GroupName,",
      "  '${9:GROUP_TYPE}' AS GroupType,",
      "  '${10:TRAINING_PERIOD}' AS TrainingPeriod,",
      "  'EVIDENCE' AS Evidence,",
      "  DATE AS Date,",
      "  'VPN_TOR' AS BehaviourMetricType,",
      "  VPN_TOR AS BehaviourMetricKey,",
      "  count(*) AS BehaviourMetricValue,",
      "  '${11:RULE_DESC}' AS AnomalyDescription,",
      "  'Transaction' AS AnomalyIdentifiedLevel,",
      "  '[]' AS ThresholdValueList,",
      "  min(TRANSACTIONSTARTTIME) AS FirstSeenStartTime,",
      "  max(TRANSACTIONSTARTTIME) AS LastSeenStartTime",
      "FROM rule_data",
      "GROUP BY MOBILENUMBER, VPN_TOR, DATE, target_name",
      "HAVING BehaviourMetricValue ${12:>= 1}",
    ].join("\n"),
  }
];